### ISSUE TITLE
GitHub Actions: Migrate the full test suite from Travis CI to GHA

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/doFuture#65]
```
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: release
      env:
        - R_FUTURE_FORK_ENABLE=false
    - os: linux
      r: release
      env:
        - R_FUTURE_PLAN=multisession
    - os: linux
      r: release
      r_github_packages:
        - HenrikBengtsson/future@develop
      env:
        - R_FUTURE_GLOBALS_ONREFERENCE=warning
        - R_FUTURE_RNG_ONMISUSE=error
    - os: linux
      r: devel
      r_packages:
        - doRNG
        - future.batchtools
        - plyr
    - os: linux
      r: devel
      r_packages:
        - doRNG
      r_check_args: --timings
      env: NB='w/out --as-cran' ## Just a label
    - os: linux
      r: devel
      r_packages:
        - doRNG
        - plyr
      r_check_args: --timings
      env: NB='w/out --as-cran + plyr' ## Just a label
    - os: linux
      r: devel
      r_packages:
        - doRNG
        - future.batchtools
        - plyr
      r_check_args: --timings
      env: NB='w/out --as-cran + pkgs' ## Just a label
    - os: linux
      r: devel
      env:
        - R_KEEP_PKG_SOURCE=yes
        - _R_S3_METHOD_LOOKUP_BASEENV_AFTER_GLOBALENV_=true
        - _R_S3_METHOD_LOOKUP_USE_TOPENV_AS_DEFENV_=true
        - _R_CHECK_CONNECTIONS_LEFT_OPEN_=true
        - _R_CHECK_LENGTH_1_CONDITION_=true
        - _R_CHECK_LENGTH_1_LOGIC2_=true
        - _R_CLASS_MATRIX_ARRAY_=true
    - os: osx
      r: oldrel
    - os: osx
      r: release
    - os: linux
      r: release
      r_packages:
        - covr
      script:
        - R CMD build --no-build-vignettes --no-manual .
        - Rscript -e 'covr::codecov(quiet=FALSE)'
      env: NB='w/ covr' ## Just a label

    - os: linux
      r: release
      bioc_packages:
        - BiocParallel
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ BiocParallel' ## Just a label
        - R_FUTURE_RNG_ONMISUSE=error
      script:
        - R CMD build .
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e 'if (!grepl("[ci cache]", Sys.getenv("TRAVIS_COMMIT_MESSAGE"), fixed = TRUE)) source("tests/zzz,BiocParallel.R", chdir = TRUE, echo = TRUE)'

    - os: linux
      r: release
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ foreach' ## Just a label
        - _R_CHECK_TESTSETS_=foreach
        - _R_CHECK_FUTURE_STRATEGIES_=sequential,multicore,multisession,batchtools_local
        - R_FUTURE_RNG_ONMISUSE=error
      script:
        - R CMD build .
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e 'if (!grepl("[ci cache]", Sys.getenv("TRAVIS_COMMIT_MESSAGE"), fixed = TRUE)) source("tests/zzz_opt-in,foreach,examples.R", chdir = TRUE, echo = TRUE)'
    - os: linux
      r: release
      r_packages:
        - future.batchtools
        - NMF
        - cluster
        - lattice
        - MASS
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ NMF' ## Just a label
        - _R_CHECK_TESTSETS_=NMF
        - _R_CHECK_FUTURE_STRATEGIES_=sequential,multicore,multisession,batchtools_local
        - R_FUTURE_RNG_ONMISUSE=warning ## "error" not possible; has RNG mistake
      script:
        - R CMD build .
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e 'if (!grepl("[ci cache]", Sys.getenv("TRAVIS_COMMIT_MESSAGE"), fixed = TRUE)) source("tests/zzz_opt-in,NMF,examples.R", chdir = TRUE, echo = TRUE)'
    - os: linux
      r: release
      r_packages:
        - future.batchtools
        - TSP
        - cluster
        - foreign
        - lattice
        - MASS
        - maps
        - sp
        - maptools
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ TSP' ## Just a label
        - _R_CHECK_TESTSETS_=TSP
        - _R_CHECK_FUTURE_STRATEGIES_=sequential,multicore,multisession,batchtools_local
        - R_FUTURE_RNG_ONMISUSE=warning ## "error" not possible; has RNG mistake
      script:
        - R CMD build .
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e 'if (!grepl("[ci cache]", Sys.getenv("TRAVIS_COMMIT_MESSAGE"), fixed = TRUE)) source("tests/zzz_opt-in,TSP,examples.R", chdir = TRUE, echo = TRUE)'
    - os: linux
      r: release
      r_packages:
        - future.batchtools
        - glmnet
        - cluster
        - lattice
        - MASS
        - Matrix
        - survival
        - lars
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ glmnet' ## Just a label
        - _R_CHECK_TESTSETS_=glmnet
        - _R_CHECK_FUTURE_STRATEGIES_=sequential,multicore,multisession,batchtools_local
        - R_FUTURE_RNG_ONMISUSE=error
      script:
        - R CMD build .
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e 'if (!grepl("[ci cache]", Sys.getenv("TRAVIS_COMMIT_MESSAGE"), fixed = TRUE)) source("tests/zzz_opt-in,glmnet,examples.R", chdir = TRUE, echo = TRUE)'
    - os: linux
      r: release
      r_packages:
        - future.batchtools
        - plyr
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ plyr & sequential' ## Just a label
        - _R_CHECK_TESTSETS_=plyr
        - _R_CHECK_FUTURE_STRATEGIES_=sequential
        - R_FUTURE_RNG_ONMISUSE=error
      script:
        - R CMD build .
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e 'if (!grepl("[ci cache]", Sys.getenv("TRAVIS_COMMIT_MESSAGE"), fixed = TRUE)) source("tests/zzz_opt-in,plyr,examples.R", chdir = TRUE, echo = TRUE)'
    - os: linux
      r: release
      r_packages:
        - future.batchtools
        - plyr
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ plyr & multisession' ## Just a label
        - _R_CHECK_TESTSETS_=plyr
        - _R_CHECK_FUTURE_STRATEGIES_=multisession
        - R_FUTURE_RNG_ONMISUSE=error
      script:
        - R CMD build .
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e 'if (!grepl("[ci cache]", Sys.getenv("TRAVIS_COMMIT_MESSAGE"), fixed = TRUE)) source("tests/zzz_opt-in,plyr,examples.R", chdir = TRUE, echo = TRUE)'
    - os: linux
      r: release
      r_packages:
        - future.batchtools
        - plyr
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ plyr & future.batchtools' ## Just a label
        - _R_CHECK_TESTSETS_=plyr
        - _R_CHECK_FUTURE_STRATEGIES_=batchtools_local
        - R_FUTURE_RNG_ONMISUSE=error
      script:
        - R CMD build .
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e 'if (!grepl("[ci cache]", Sys.getenv("TRAVIS_COMMIT_MESSAGE"), fixed = TRUE)) source("tests/zzz_opt-in,plyr,examples.R", chdir = TRUE, echo = TRUE)'
    - os: linux
      r: release
      r_packages:
        - plyr
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ plyr & future.callr' ## Just a label
        - _R_CHECK_TESTSETS_=plyr
        - _R_CHECK_FUTURE_STRATEGIES_="future.callr::callr"
        - R_FUTURE_RNG_ONMISUSE=error
      script:
        - R CMD build .
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e "source('https://install-github.me/HenrikBengtsson/future.callr')"
        - Rscript -e 'if (!grepl("[ci cache]", Sys.getenv("TRAVIS_COMMIT_MESSAGE"), fixed = TRUE)) source("tests/zzz_opt-in,plyr,examples.R", chdir = TRUE, echo = TRUE)'
    - os: linux
      r: release
      r_packages:
        - future.batchtools
        - caret
        - class
        - foreign
        - lattice
        - MASS
        - Matrix
        - nlme
        - nnet
        - rpart
        - survival
        - BradleyTerry2
        - e1071
        - earth
        - fastICA
        - gam
        - ipred
        - kernlab
        - klaR
        - ellipse
        - mda
        - mgcv
        - mlbench
        - MLmetrics
        - party
        - pls
        - pROC
        - proxy
        - randomForest
        - RANN
        - spls
        - subselect
        - pamr
        - Cubist
        - pls
        - recipes
        - mboost
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ caret & sequential' ## Just a label
        - _R_CHECK_TESTSETS_=caret
        - _R_CHECK_FUTURE_STRATEGIES_=sequential
        - R_FUTURE_RNG_ONMISUSE=warning ## "error" not possible; has RNG mistake
      script:
        - R CMD build .
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e 'if (!grepl("[ci cache]", Sys.getenv("TRAVIS_COMMIT_MESSAGE"), fixed = TRUE)) source("tests/zzz_opt-in,caret,examples.R", chdir = TRUE, echo = TRUE)'
    - os: linux
      r: release
      r_packages:
        - future.batchtools
        - caret
        - class
        - foreign
        - lattice
        - MASS
        - Matrix
        - nlme
        - nnet
        - rpart
        - survival
        - BradleyTerry2
        - e1071
        - earth
        - fastICA
        - gam
        - ipred
        - kernlab
        - klaR
        - ellipse
        - mda
        - mgcv
        - mlbench
        - MLmetrics
        - party
        - pls
        - pROC
        - proxy
        - randomForest
        - RANN
        - spls
        - subselect
        - pamr
        - Cubist
        - pls
        - recipes
        - mboost
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ caret & multisession' ## Just a label
        - _R_CHECK_TESTSETS_=caret
        - _R_CHECK_FUTURE_STRATEGIES_=multisession
        - R_FUTURE_RNG_ONMISUSE=warning ## "error" not possible; has RNG mistake
      script:
        - R CMD build .
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e 'if (!grepl("[ci cache]", Sys.getenv("TRAVIS_COMMIT_MESSAGE"), fixed = TRUE)) source("tests/zzz_opt-in,caret,examples.R", chdir = TRUE, echo = TRUE)'
    - os: linux
      r: release
      r_packages:
        - future.batchtools
        - caret
        - class
        - foreign
        - lattice
        - MASS
        - Matrix
        - nlme
        - nnet
        - rpart
        - survival
        - BradleyTerry2
        - e1071
        - earth
        - fastICA
        - gam
        - ipred
        - kernlab
        - klaR
        - ellipse
        - mda
        - mgcv
        - mlbench
        - MLmetrics
        - party
        - pls
        - pROC
        - proxy
        - randomForest
        - RANN
        - spls
        - subselect
        - pamr
        - Cubist
        - pls
        - recipes
        - mboost
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ caret & batchtools' ## Just a label
        - _R_CHECK_TESTSETS_=caret
        - _R_CHECK_FUTURE_STRATEGIES_=batchtools_local
        - R_FUTURE_RNG_ONMISUSE=warning ## "error" not possible; has RNG mistake
      script:
        - R CMD build .
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e 'if (!grepl("[ci cache]", Sys.getenv("TRAVIS_COMMIT_MESSAGE"), fixed = TRUE)) source("tests/zzz_opt-in,caret,examples.R", chdir = TRUE, echo = TRUE)'
```

**Comment by HenrikBengtsson** [comment]
Remaining as of 2021-08-12:

```
    - os: linux
      r: release
      env:
        - R_FUTURE_FORK_ENABLE=false
    - os: linux
      r: release
      r_github_packages:
        - HenrikBengtsson/future@develop
      env:
        - R_FUTURE_GLOBALS_ONREFERENCE=warning
        - R_FUTURE_RNG_ONMISUSE=error
    - os: linux
      r: devel
      r_packages:
        - doRNG
        - future.batchtools
        - plyr
    - os: linux
      r: devel
      r_packages:
        - doRNG
      r_check_args: --timings
      env: NB='w/out --as-cran' ## Just a label
    - os: linux
      r: devel
      r_packages:
        - doRNG
        - plyr
      r_check_args: --timings
      env: NB='w/out --as-cran + plyr' ## Just a label
    - os: linux
      r: devel
      r_packages:
        - doRNG
        - future.batchtools
        - plyr
      r_check_args: --timings
      env: NB='w/out --as-cran + pkgs' ## Just a label
    - os: linux
      r: devel
      env:
        - R_KEEP_PKG_SOURCE=yes
        - _R_S3_METHOD_LOOKUP_BASEENV_AFTER_GLOBALENV_=true
        - _R_S3_METHOD_LOOKUP_USE_TOPENV_AS_DEFENV_=true
        - _R_CHECK_CONNECTIONS_LEFT_OPEN_=true
        - _R_CHECK_LENGTH_1_CONDITION_=true
        - _R_CHECK_LENGTH_1_LOGIC2_=true
        - _R_CLASS_MATRIX_ARRAY_=true
    - os: osx
      r: oldrel
    - os: osx
      r: release
    - os: linux
      r: release
      r_packages:
        - covr
      script:
        - R CMD build --no-build-vignettes --no-manual .
        - Rscript -e 'covr::codecov(quiet=FALSE)'
      env: NB='w/ covr' ## Just a label

    - os: linux
      r: release
      bioc_packages:
        - BiocParallel
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ BiocParallel' ## Just a label
        - R_FUTURE_RNG_ONMISUSE=error
      script:
        - R CMD build .
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e 'if (!grepl("[ci cache]", Sys.getenv("TRAVIS_COMMIT_MESSAGE"), fixed = TRUE)) source("tests/zzz,BiocParallel.R", chdir = TRUE, echo = TRUE)'

    - os: linux
      r: release
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ foreach' ## Just a label
        - _R_CHECK_TESTSETS_=foreach
        - _R_CHECK_FUTURE_STRATEGIES_=sequential,multicore,multisession,batchtools_local
        - R_FUTURE_RNG_ONMISUSE=error
      script:
        - R CMD build .
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e 'if (!grepl("[ci cache]", Sys.getenv("TRAVIS_COMMIT_MESSAGE"), fixed = TRUE)) source("tests/zzz_opt-in,foreach,examples.R", chdir = TRUE, echo = TRUE)'
    - os: linux
      r: release
      r_packages:
        - future.batchtools
        - NMF
        - cluster
        - lattice
        - MASS
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ NMF' ## Just a label
        - _R_CHECK_TESTSETS_=NMF
        - _R_CHECK_FUTURE_STRATEGIES_=sequential,multicore,multisession,batchtools_local
        - R_FUTURE_RNG_ONMISUSE=warning ## "error" not possible; has RNG mistake
      script:
        - R CMD build .
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e 'if (!grepl("[ci cache]", Sys.getenv("TRAVIS_COMMIT_MESSAGE"), fixed = TRUE)) source("tests/zzz_opt-in,NMF,examples.R", chdir = TRUE, echo = TRUE)'
    - os: linux
      r: release
      r_packages:
        - future.batchtools
        - TSP
        - cluster
        - foreign
        - lattice
        - MASS
        - maps
        - sp
        - maptools
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ TSP' ## Just a label
        - _R_CHECK_TESTSETS_=TSP
        - _R_CHECK_FUTURE_STRATEGIES_=sequential,multicore,multisession,batchtools_local
        - R_FUTURE_RNG_ONMISUSE=warning ## "error" not possible; has RNG mistake
      script:
        - R CMD build .
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e 'if (!grepl("[ci cache]", Sys.getenv("TRAVIS_COMMIT_MESSAGE"), fixed = TRUE)) source("tests/zzz_opt-in,TSP,examples.R", chdir = TRUE, echo = TRUE)'
    - os: linux
      r: release
      r_packages:
        - future.batchtools
        - glmnet
        - cluster
        - lattice
        - MASS
        - Matrix
        - survival
        - lars
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ glmnet' ## Just a label
        - _R_CHECK_TESTSETS_=glmnet
        - _R_CHECK_FUTURE_STRATEGIES_=sequential,multicore,multisession,batchtools_local
        - R_FUTURE_RNG_ONMISUSE=error
      script:
        - R CMD build .
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e 'if (!grepl("[ci cache]", Sys.getenv("TRAVIS_COMMIT_MESSAGE"), fixed = TRUE)) source("tests/zzz_opt-in,glmnet,examples.R", chdir = TRUE, echo = TRUE)'
    - os: linux
      r: release
      r_packages:
        - future.batchtools
        - plyr
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ plyr & sequential' ## Just a label
        - _R_CHECK_TESTSETS_=plyr
        - _R_CHECK_FUTURE_STRATEGIES_=sequential
        - R_FUTURE_RNG_ONMISUSE=error
      script:
        - R CMD build .
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e 'if (!grepl("[ci cache]", Sys.getenv("TRAVIS_COMMIT_MESSAGE"), fixed = TRUE)) source("tests/zzz_opt-in,plyr,examples.R", chdir = TRUE, echo = TRUE)'
    - os: linux
      r: release
      r_packages:
        - future.batchtools
        - plyr
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ plyr & multisession' ## Just a label
        - _R_CHECK_TESTSETS_=plyr
        - _R_CHECK_FUTURE_STRATEGIES_=multisession
        - R_FUTURE_RNG_ONMISUSE=error
      script:
        - R CMD build .
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e 'if (!grepl("[ci cache]", Sys.getenv("TRAVIS_COMMIT_MESSAGE"), fixed = TRUE)) source("tests/zzz_opt-in,plyr,examples.R", chdir = TRUE, echo = TRUE)'
    - os: linux
      r: release
      r_packages:
        - future.batchtools
        - plyr
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ plyr & future.batchtools' ## Just a label
        - _R_CHECK_TESTSETS_=plyr
        - _R_CHECK_FUTURE_STRATEGIES_=batchtools_local
        - R_FUTURE_RNG_ONMISUSE=error
      script:
        - R CMD build .
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e 'if (!grepl("[ci cache]", Sys.getenv("TRAVIS_COMMIT_MESSAGE"), fixed = TRUE)) source("tests/zzz_opt-in,plyr,examples.R", chdir = TRUE, echo = TRUE)'
    - os: linux
      r: release
      r_packages:
        - plyr
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ plyr & future.callr' ## Just a label
        - _R_CHECK_TESTSETS_=plyr
        - _R_CHECK_FUTURE_STRATEGIES_="future.callr::callr"
        - R_FUTURE_RNG_ONMISUSE=error
      script:
        - R CMD build .
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e "source('https://install-github.me/HenrikBengtsson/future.callr')"
        - Rscript -e 'if (!grepl("[ci cache]", Sys.getenv("TRAVIS_COMMIT_MESSAGE"), fixed = TRUE)) source("tests/zzz_opt-in,plyr,examples.R", chdir = TRUE, echo = TRUE)'
    - os: linux
      r: release
      r_packages:
        - future.batchtools
        - caret
        - class
        - foreign
        - lattice
        - MASS
        - Matrix
        - nlme
        - nnet
        - rpart
        - survival
        - BradleyTerry2
        - e1071
        - earth
        - fastICA
        - gam
        - ipred
        - kernlab
        - klaR
        - ellipse
        - mda
        - mgcv
        - mlbench
        - MLmetrics
        - party
        - pls
        - pROC
        - proxy
        - randomForest
        - RANN
        - spls
        - subselect
        - pamr
        - Cubist
        - pls
        - recipes
        - mboost
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ caret & sequential' ## Just a label
        - _R_CHECK_TESTSETS_=caret
        - _R_CHECK_FUTURE_STRATEGIES_=sequential
        - R_FUTURE_RNG_ONMISUSE=warning ## "error" not possible; has RNG mistake
      script:
        - R CMD build .
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e 'if (!grepl("[ci cache]", Sys.getenv("TRAVIS_COMMIT_MESSAGE"), fixed = TRUE)) source("tests/zzz_opt-in,caret,examples.R", chdir = TRUE, echo = TRUE)'
    - os: linux
      r: release
      r_packages:
        - future.batchtools
        - caret
        - class
        - foreign
        - lattice
        - MASS
        - Matrix
        - nlme
        - nnet
        - rpart
        - survival
        - BradleyTerry2
        - e1071
        - earth
        - fastICA
        - gam
        - ipred
        - kernlab
        - klaR
        - ellipse
        - mda
        - mgcv
        - mlbench
        - MLmetrics
        - party
        - pls
        - pROC
        - proxy
        - randomForest
        - RANN
        - spls
        - subselect
        - pamr
        - Cubist
        - pls
        - recipes
        - mboost
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ caret & multisession' ## Just a label
        - _R_CHECK_TESTSETS_=caret
        - _R_CHECK_FUTURE_STRATEGIES_=multisession
        - R_FUTURE_RNG_ONMISUSE=warning ## "error" not possible; has RNG mistake
      script:
        - R CMD build .
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e 'if (!grepl("[ci cache]", Sys.getenv("TRAVIS_COMMIT_MESSAGE"), fixed = TRUE)) source("tests/zzz_opt-in,caret,examples.R", chdir = TRUE, echo = TRUE)'
    - os: linux
      r: release
      r_packages:
        - future.batchtools
        - caret
        - class
        - foreign
        - lattice
        - MASS
        - Matrix
        - nlme
        - nnet
        - rpart
        - survival
        - BradleyTerry2
        - e1071
        - earth
        - fastICA
        - gam
        - ipred
        - kernlab
        - klaR
        - ellipse
        - mda
        - mgcv
        - mlbench
        - MLmetrics
        - party
        - pls
        - pROC
        - proxy
        - randomForest
        - RANN
        - spls
        - subselect
        - pamr
        - Cubist
        - pls
        - recipes
        - mboost
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ caret & batchtools' ## Just a label
        - _R_CHECK_TESTSETS_=caret
        - _R_CHECK_FUTURE_STRATEGIES_=batchtools_local
        - R_FUTURE_RNG_ONMISUSE=warning ## "error" not possible; has RNG mistake
      script:
        - R CMD build .
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e 'if (!grepl("[ci cache]", Sys.getenv("TRAVIS_COMMIT_MESSAGE"), fixed = TRUE)) source("tests/zzz_opt-in,caret,examples.R", chdir = TRUE, echo = TRUE)'
```
